### ISSUE TITLE
Add ttf fonts to the repository

### ISSUE THREAD

**Issue by insolor** [dfint/df-font-generator#1]
Maybe except for Lucida Console, because it looks rather ugly without antialiasing. May be we'll add some other fonts instead.
Don't forget to add font's license too.

**Comment by shevernitskiy** [comment]
Done with 442e1a30276b562dbc8dff6dde40c9f95db20807

**Comment by insolor** [comment]
@shevernitskiy quote: "Don't forget to add font's license too."
